version: "3.9"

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" #port open container
    env_file:
      - .env.local
    volumes:
      - /[yourfolder]/[yourfolder]/[yourfolder]/Portfolio:/app
      - /app/node_modules
    restart: unless-stopped
