version: "3.9"

services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" #port untuk di expose
    env_file:
      - .env.local
    volumes:
      - ./public:/app/public
      - ./package.json:/app/package.json
    restart: always
